using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace Loyufei.InputSystem
{
    /// <summary>
    /// Unity InputSystem 和 XInputDonet 橋接輸入
    /// </summary>
    [Serializable]
    public enum EInputCode
    {
        #region Unity InputSystem (KeyBoard, Mouse)

        None              = KeyCode.None, 
        Backspace         = KeyCode.Backspace,
        Tab               = KeyCode.Tab,
        Clear             = KeyCode.Clear,
        Return            = KeyCode.Return,
        Pause             = KeyCode.Pause,
        Escape            = KeyCode.Escape,
        Space             = KeyCode.Space,
        Exclaim           = KeyCode.Exclaim,
        DoubleQuote       = KeyCode.DoubleQuote,
        Hash              = KeyCode.Hash,
        Dollar            = KeyCode.Dollar,
        Percent           = KeyCode.Percent,
        Ampersand         = KeyCode.Ampersand,
        Quote             = KeyCode.Quote,
        LeftParen         = KeyCode.LeftParen,
        RightParen        = KeyCode.RightParen,
        Asterisk          = KeyCode.Asterisk,
        Plus              = KeyCode.Plus,
        Comma             = KeyCode.Comma,
        Minus             = KeyCode.Minus,
        Period            = KeyCode.Period,
        Slash             = KeyCode.Slash,
        Alpha0            = KeyCode.Alpha0,
        Alpha1            = KeyCode.Alpha1,
        Alpha2            = KeyCode.Alpha2,
        Alpha3            = KeyCode.Alpha3,
        Alpha4            = KeyCode.Alpha4,
        Alpha5            = KeyCode.Alpha5,
        Alpha6            = KeyCode.Alpha6,
        Alpha7            = KeyCode.Alpha7,
        Alpha8            = KeyCode.Alpha8,
        Alpha9            = KeyCode.Alpha9,
        Colon             = KeyCode.Colon,
        Semicolon         = KeyCode.Semicolon,
        Less              = KeyCode.Less,
        Equals            = KeyCode.Equals,
        Greater           = KeyCode.Greater,
        Question          = KeyCode.Question,
        At                = KeyCode.At,
        LeftBracket       = KeyCode.LeftBracket,
        Backslash         = KeyCode.Backslash,
        RightBracket      = KeyCode.RightBracket,
        Caret             = KeyCode.Caret,
        Underscore        = KeyCode.Underscore,
        BackQuote         = KeyCode.BackQuote,
        A                 = KeyCode.A,
        B                 = KeyCode.B,
        C                 = KeyCode.C,
        D                 = KeyCode.D,
        E                 = KeyCode.E,
        F                 = KeyCode.F,
        G                 = KeyCode.G,
        H                 = KeyCode.H,
        I                 = KeyCode.I,
        J                 = KeyCode.J,
        K                 = KeyCode.K,
        L                 = KeyCode.L,
        M                 = KeyCode.M,
        N                 = KeyCode.N,
        O                 = KeyCode.O,
        P                 = KeyCode.P,
        Q                 = KeyCode.Q,
        R                 = KeyCode.R,
        S                 = KeyCode.S,
        T                 = KeyCode.T,
        U                 = KeyCode.U,
        V                 = KeyCode.V,
        W                 = KeyCode.W,
        X                 = KeyCode.X,
        Y                 = KeyCode.Y,
        Z                 = KeyCode.Z,
        LeftCurlyBracket  = KeyCode.LeftCurlyBracket,
        Pipe              = KeyCode.Pipe,
        RightCurlyBracket = KeyCode.RightCurlyBracket,
        Tilde             = KeyCode.Tilde,
        Delete            = KeyCode.Delete,
        Keypad0           = KeyCode.Keypad0,
        Keypad1           = KeyCode.Keypad1,
        Keypad2           = KeyCode.Keypad2,
        Keypad3           = KeyCode.Keypad3,
        Keypad4           = KeyCode.Keypad4,
        Keypad5           = KeyCode.Keypad5,
        Keypad6           = KeyCode.Keypad6,
        Keypad7           = KeyCode.Keypad7,
        Keypad8           = KeyCode.Keypad8,
        Keypad9           = KeyCode.Keypad9,
        KeypadPeriod      = KeyCode.KeypadPeriod,
        KeypadDivide      = KeyCode.KeypadDivide,
        KeypadMultiply    = KeyCode.KeypadMultiply,
        KeypadMinus       = KeyCode.KeypadMinus,
        KeypadPlus        = KeyCode.KeypadPlus,
        KeypadEnter       = KeyCode.KeypadEnter,
        KeypadEquals      = KeyCode.KeypadEquals,
        UpArrow           = KeyCode.UpArrow,
        DownArrow         = KeyCode.DownArrow,
        RightArrow        = KeyCode.RightArrow,
        LeftArrow         = KeyCode.LeftArrow,
        Insert            = KeyCode.Insert,
        Home              = KeyCode.Home,
        End               = KeyCode.End,
        PageUp            = KeyCode.PageUp,
        PageDown          = KeyCode.PageDown,
        F1                = KeyCode.F1,
        F2                = KeyCode.F2,
        F3                = KeyCode.F3,
        F4                = KeyCode.F4,
        F5                = KeyCode.F5,
        F6                = KeyCode.F6,
        F7                = KeyCode.F7,
        F8                = KeyCode.F8,
        F9                = KeyCode.F9,
        F10               = KeyCode.F10,
        F11               = KeyCode.F11,
        F12               = KeyCode.F12,
        F13               = KeyCode.F13,
        F14               = KeyCode.F14,
        F15               = KeyCode.F15,
        Numlock           = KeyCode.Numlock,
        CapsLock          = KeyCode.CapsLock,
        ScrollLock        = KeyCode.ScrollLock,
        RightShift        = KeyCode.RightShift,
        LeftShift         = KeyCode.LeftShift,
        RightControl      = KeyCode.RightControl,
        LeftControl       = KeyCode.LeftControl,
        RightAlt          = KeyCode.RightAlt,
        LeftAlt           = KeyCode.LeftAlt,
        RightMeta         = KeyCode.RightMeta,
        LeftApple         = KeyCode.LeftApple,
        LeftWindows       = KeyCode.LeftWindows,
        RightWindows      = KeyCode.RightWindows,
        AltGr             = KeyCode.AltGr,
        Help              = KeyCode.Help,
        Print             = KeyCode.Print,
        SysReq            = KeyCode.SysReq,
        Break             = KeyCode.Break,
        Menu              = KeyCode.Menu,
        Mouse0            = KeyCode.Mouse0,
        Mouse1            = KeyCode.Mouse1,
        Mouse2            = KeyCode.Mouse2,
        Mouse3            = KeyCode.Mouse3,
        Mouse4            = KeyCode.Mouse4,
        Mouse5            = KeyCode.Mouse5,
        Mouse6            = KeyCode.Mouse6,

        #endregion

        #region XInputDonet GameController Input

        #endregion
    }
}